
실습 과제1: NumPy를 활용한 행렬 변형 실습
문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.

문제 2: 새로운 축 추가
행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.



In [2]:
import numpy as np

x1 = np.random.rand(6,5)

x1

array([[0.59554372, 0.5713927 , 0.6530626 , 0.88203744, 0.94323231],
       [0.81877969, 0.97201346, 0.35248546, 0.62434805, 0.6236084 ],
       [0.34878885, 0.66532798, 0.31121817, 0.42816517, 0.73562129],
       [0.76636816, 0.68066487, 0.92234691, 0.52812906, 0.15987631],
       [0.5809622 , 0.29178588, 0.22976585, 0.47766906, 0.30806494],
       [0.69226428, 0.55782768, 0.36640164, 0.07616851, 0.38348977]])

In [ ]:
#x2 = x1[:, np.newaxis]
x2 = x1.reshape(6,1,5) # 원소의 갯수가 고정일 때 사용

print(x2.shape)

(6, 1, 5)


In [91]:
x3 = x2[2, :]

x3[:] = 0.3

x2

array([[[0.58817401, 0.68822413, 0.9118182 , 0.90943018, 0.58450652]],

       [[0.64786816, 0.22517223, 0.73562036, 0.84941572, 0.25271359]],

       [[0.3       , 0.3       , 0.3       , 0.3       , 0.3       ]],

       [[0.55170821, 0.80327518, 0.99778306, 0.24897378, 0.48083958]],

       [[0.29617075, 0.73249387, 0.85867123, 0.22560809, 0.54854686]],

       [[0.3855521 , 0.02951184, 0.15740165, 0.56860113, 0.74638291]]])

In [ ]:
x4 = x1[np.newaxis, :]

print(x4.shape)
print(x4)

x5 = x1[:, :, np.newaxis]

print(x5.shape)
print(x5)

(1, 6, 5)
[[[0.03944228 0.54256772 0.07597629 0.35803039 0.09569753]
  [0.63788785 0.37006254 0.07980049 0.59249725 0.7686657 ]
  [0.33040331 0.98372481 0.21223149 0.73027467 0.05011889]
  [0.99935431 0.18907856 0.56883576 0.74798866 0.42167922]
  [0.66089408 0.13491343 0.70701849 0.92264923 0.75835559]
  [0.52519301 0.65978514 0.13266036 0.0799801  0.98220402]]]
(6, 5, 1)
[[[0.03944228]
  [0.54256772]
  [0.07597629]
  [0.35803039]
  [0.09569753]]

 [[0.63788785]
  [0.37006254]
  [0.07980049]
  [0.59249725]
  [0.7686657 ]]

 [[0.33040331]
  [0.98372481]
  [0.21223149]
  [0.73027467]
  [0.05011889]]

 [[0.99935431]
  [0.18907856]
  [0.56883576]
  [0.74798866]
  [0.42167922]]

 [[0.66089408]
  [0.13491343]
  [0.70701849]
  [0.92264923]
  [0.75835559]]

 [[0.52519301]
  [0.65978514]
  [0.13266036]
  [0.0799801 ]
  [0.98220402]]]


In [97]:
x6 = x5[3:]

x6[:] = 0.8

print(x5)

[[[0.08631003 0.97979846 0.33995099 0.44964585 0.42580538]]

 [[0.08086421 0.58899553 0.21539812 0.69991417 0.14311927]]

 [[0.5246216  0.98322586 0.19271915 0.16780166 0.29928239]]

 [[0.8        0.8        0.8        0.8        0.8       ]]

 [[0.8        0.8        0.8        0.8        0.8       ]]

 [[0.8        0.8        0.8        0.8        0.8       ]]]
